name=Keypad
version=0.1.2
author=Thomas Seren
maintainer=Community https://github.com/elSereno-T/Keypad
sentence=Keypad is a library for using matrix style keypads with the Arduino.
paragraph=This library is based upon the Keypad library by Mark Stanley, Alexander Brevig (https://github.com/Chris--A/Keypad)
category=Device Control
url=https://github.com/elSereno-T/Keypad
architectures=*